/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const snapshot = [
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1582905952',
            max: 0,
            min: 0,
            name: 'method',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_2279338944',
        indexes: ['CREATE INDEX `idx_mfas_collectionRef_recordRef` ON `_mfas` (collectionRef,recordRef)'],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_mfas',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 8,
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 0,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '',
            hidden: true,
            id: 'text3866985172',
            max: 0,
            min: 0,
            name: 'sentTo',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_1638494021',
        indexes: ['CREATE INDEX `idx_otps_collectionRef_recordRef` ON `_otps` (collectionRef, recordRef)'],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_otps',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text2462348188',
            max: 0,
            min: 0,
            name: 'provider',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1044722854',
            max: 0,
            min: 0,
            name: 'providerId',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_2281828961',
        indexes: [
          'CREATE UNIQUE INDEX `idx_externalAuths_record_provider` ON `_externalAuths` (collectionRef, recordRef, provider)',
          'CREATE UNIQUE INDEX `idx_externalAuths_collection_provider` ON `_externalAuths` (collectionRef, provider, providerId)',
        ],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_externalAuths',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text4228609354',
            max: 0,
            min: 0,
            name: 'fingerprint',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_4275539003',
        indexes: [
          'CREATE UNIQUE INDEX `idx_authOrigins_unique_pairs` ON `_authOrigins` (collectionRef, recordRef, fingerprint)',
        ],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_authOrigins',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        authAlert: {
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location.</p>\n<p>If this was you, you may disregard this email.</p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'Login from a new location',
          },
          enabled: true,
        },
        authRule: '',
        authToken: {
          duration: 86400,
        },
        confirmEmailChangeTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">Confirm new email</a>\n</p>\n<p><i>If you didn\'t ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Confirm your {APP_NAME} new email address',
        },
        createRule: null,
        deleteRule: null,
        emailChangeToken: {
          duration: 1800,
        },
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 0,
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 8,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '[a-zA-Z0-9]{50}',
            hidden: true,
            id: 'text2504183744',
            max: 60,
            min: 30,
            name: 'tokenKey',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            exceptDomains: null,
            hidden: false,
            id: 'email3885137012',
            name: 'email',
            onlyDomains: null,
            presentable: false,
            required: true,
            system: true,
            type: 'email',
          },
          {
            hidden: false,
            id: 'bool1547992806',
            name: 'emailVisibility',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'bool256245529',
            name: 'verified',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        fileToken: {
          duration: 180,
        },
        id: 'pbc_3142635823',
        indexes: [
          'CREATE UNIQUE INDEX `idx_tokenKey_pbc_3142635823` ON `_superusers` (`tokenKey`)',
          "CREATE UNIQUE INDEX `idx_email_pbc_3142635823` ON `_superusers` (`email`) WHERE `email` != ''",
        ],
        listRule: null,
        manageRule: null,
        mfa: {
          duration: 1800,
          enabled: false,
          rule: '',
        },
        name: '_superusers',
        oauth2: {
          enabled: false,
          mappedFields: {
            avatarURL: '',
            id: '',
            name: '',
            username: '',
          },
        },
        otp: {
          duration: 180,
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'OTP for {APP_NAME}',
          },
          enabled: false,
          length: 8,
        },
        passwordAuth: {
          enabled: true,
          identityFields: ['email'],
        },
        passwordResetToken: {
          duration: 1800,
        },
        resetPasswordTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}" target="_blank" rel="noopener">Reset password</a>\n</p>\n<p><i>If you didn\'t ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Reset your {APP_NAME} password',
        },
        system: true,
        type: 'auth',
        updateRule: null,
        verificationTemplate: {
          body: '<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-verification/{TOKEN}" target="_blank" rel="noopener">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Verify your {APP_NAME} email',
        },
        verificationToken: {
          duration: 259200,
        },
        viewRule: null,
      },
      {
        authAlert: {
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location.</p>\n<p>If this was you, you may disregard this email.</p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'Login from a new location',
          },
          enabled: true,
        },
        authRule: '',
        authToken: {
          duration: 604800,
        },
        confirmEmailChangeTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">Confirm new email</a>\n</p>\n<p><i>If you didn\'t ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Confirm your {APP_NAME} new email address',
        },
        createRule: '',
        deleteRule: 'id = @request.auth.id',
        emailChangeToken: {
          duration: 1800,
        },
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 0,
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 8,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '[a-zA-Z0-9]{50}',
            hidden: true,
            id: 'text2504183744',
            max: 60,
            min: 30,
            name: 'tokenKey',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            exceptDomains: null,
            hidden: false,
            id: 'email3885137012',
            name: 'email',
            onlyDomains: null,
            presentable: false,
            required: true,
            system: true,
            type: 'email',
          },
          {
            hidden: false,
            id: 'bool1547992806',
            name: 'emailVisibility',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'bool256245529',
            name: 'verified',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1579384326',
            max: 255,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'file376926767',
            maxSelect: 1,
            maxSize: 0,
            mimeTypes: ['image/jpeg', 'image/png', 'image/svg+xml', 'image/gif', 'image/webp'],
            name: 'avatar',
            presentable: false,
            protected: false,
            required: false,
            system: false,
            thumbs: null,
            type: 'file',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        fileToken: {
          duration: 180,
        },
        id: '_pb_users_auth_',
        indexes: [
          'CREATE UNIQUE INDEX `idx_tokenKey__pb_users_auth_` ON `users` (`tokenKey`)',
          "CREATE UNIQUE INDEX `idx_email__pb_users_auth_` ON `users` (`email`) WHERE `email` != ''",
        ],
        listRule: 'id = @request.auth.id',
        manageRule: null,
        mfa: {
          duration: 1800,
          enabled: false,
          rule: '',
        },
        name: 'users',
        oauth2: {
          enabled: false,
          mappedFields: {
            avatarURL: 'avatar',
            id: '',
            name: 'name',
            username: '',
          },
        },
        otp: {
          duration: 180,
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'OTP for {APP_NAME}',
          },
          enabled: false,
          length: 8,
        },
        passwordAuth: {
          enabled: true,
          identityFields: ['email'],
        },
        passwordResetToken: {
          duration: 1800,
        },
        resetPasswordTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}" target="_blank" rel="noopener">Reset password</a>\n</p>\n<p><i>If you didn\'t ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Reset your {APP_NAME} password',
        },
        system: false,
        type: 'auth',
        updateRule: 'id = @request.auth.id',
        verificationTemplate: {
          body: '<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-verification/{TOKEN}" target="_blank" rel="noopener">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Verify your {APP_NAME} email',
        },
        verificationToken: {
          duration: 259200,
        },
        viewRule: 'id = @request.auth.id',
      },
      {
        id: 'pbc_1245181609',
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        name: 'manager',
        type: 'auth',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 0,
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 8,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '[a-zA-Z0-9]{50}',
            hidden: true,
            id: 'text2504183744',
            max: 60,
            min: 30,
            name: 'tokenKey',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            exceptDomains: null,
            hidden: false,
            id: 'email3885137012',
            name: 'email',
            onlyDomains: null,
            presentable: false,
            required: true,
            system: true,
            type: 'email',
          },
          {
            hidden: false,
            id: 'bool1547992806',
            name: 'emailVisibility',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'bool256245529',
            name: 'verified',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        indexes: [
          'CREATE UNIQUE INDEX `idx_tokenKey_pbc_1245181609` ON `manager` (`tokenKey`)',
          "CREATE UNIQUE INDEX `idx_email_pbc_1245181609` ON `manager` (`email`) WHERE `email` != ''",
        ],
        system: false,
        authRule: '',
        manageRule: null,
        authAlert: {
          enabled: true,
          emailTemplate: {
            subject: 'Login from a new location',
            body: "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location.</p>\n<p>If this was you, you may disregard this email.</p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
          },
        },
        oauth2: {
          mappedFields: {
            id: '',
            name: '',
            username: '',
            avatarURL: '',
          },
          enabled: false,
        },
        passwordAuth: {
          enabled: true,
          identityFields: ['email'],
        },
        mfa: {
          enabled: false,
          duration: 1800,
          rule: '',
        },
        otp: {
          enabled: false,
          duration: 180,
          length: 8,
          emailTemplate: {
            subject: 'OTP for {APP_NAME}',
            body: "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
          },
        },
        authToken: {
          duration: 604800,
        },
        passwordResetToken: {
          duration: 1800,
        },
        emailChangeToken: {
          duration: 1800,
        },
        verificationToken: {
          duration: 259200,
        },
        fileToken: {
          duration: 180,
        },
        verificationTemplate: {
          subject: 'Verify your {APP_NAME} email',
          body: '<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-verification/{TOKEN}" target="_blank" rel="noopener">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
        },
        resetPasswordTemplate: {
          subject: 'Reset your {APP_NAME} password',
          body: '<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}" target="_blank" rel="noopener">Reset password</a>\n</p>\n<p><i>If you didn\'t ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
        },
        confirmEmailChangeTemplate: {
          subject: 'Confirm your {APP_NAME} new email address',
          body: '<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">Confirm new email</a>\n</p>\n<p><i>If you didn\'t ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
        },
      },
      {
        id: 'pbc_3533380876',
        listRule: '@request.auth.email ?~ "@ekraf.dev" && @request.headers.x_arcade_token != ""',
        viewRule: '@request.auth.email ?~ "@ekraf.dev" && @request.headers.x_arcade_token != ""',
        createRule: '@request.auth.email ?~ "@ekraf.dev" && @request.headers.x_arcade_token != ""',
        updateRule: '@request.auth.email ?~ "@ekraf.dev" && @request.headers.x_arcade_token != ""',
        deleteRule: null,
        name: 'course_enrollments',
        type: 'base',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_3414089001',
            hidden: false,
            id: 'relation2170006031',
            maxSelect: 1,
            minSelect: 0,
            name: 'profile',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_955655590',
            hidden: false,
            id: 'relation379482041',
            maxSelect: 1,
            minSelect: 0,
            name: 'course',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: 'select3910207164',
            maxSelect: 1,
            name: 'difficulty',
            presentable: false,
            required: false,
            system: false,
            type: 'select',
            values: ['easy', 'medium', 'hard'],
          },
          {
            hidden: false,
            id: 'select245846248',
            maxSelect: 1,
            name: 'label',
            presentable: false,
            required: false,
            system: false,
            type: 'select',
            values: ['skill', 'game', 'trivia', 'wmp', 'labfree', 'completion', 'special'],
          },
          {
            hidden: false,
            id: 'date2625885481',
            max: '',
            min: '',
            name: 'earned',
            presentable: false,
            required: true,
            system: false,
            type: 'date',
          },
        ],
        indexes: [],
        system: false,
      },
      {
        id: 'pbc_955655590',
        listRule: '@request.headers.x_arcade_token != ""',
        viewRule: '@request.headers.x_arcade_token != ""',
        createRule: null,
        updateRule: null,
        deleteRule: null,
        name: 'courses',
        type: 'base',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'number1462966518',
            max: null,
            min: null,
            name: 'courseid',
            onlyInt: true,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            hidden: false,
            id: 'number944913438',
            max: null,
            min: null,
            name: 'badgeid',
            onlyInt: true,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text724990059',
            max: 0,
            min: 0,
            name: 'title',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'select2363381545',
            maxSelect: 1,
            name: 'type',
            presentable: false,
            required: false,
            system: false,
            type: 'select',
            values: ['skill', 'game', 'wmp', 'trivia', 'labfree', 'completion'],
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1597481275',
            max: 0,
            min: 0,
            name: 'token',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'number3081106212',
            max: null,
            min: null,
            name: 'point',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            hidden: false,
            id: 'bool2294531711',
            name: 'fasttrack',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'bool2345864928',
            name: 'inactive',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'number3946859848',
            max: null,
            min: null,
            name: 'totallab',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            hidden: false,
            id: 'select2599078931',
            maxSelect: 1,
            name: 'level',
            presentable: false,
            required: false,
            system: false,
            type: 'select',
            values: ['introductory', 'intermediate', 'advanced'],
          },
          {
            exceptDomains: null,
            hidden: false,
            id: 'url1704280674',
            name: 'badgeurl',
            onlyDomains: null,
            presentable: false,
            required: false,
            system: false,
            type: 'url',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_2691397795',
            hidden: false,
            id: 'relation2271616787',
            maxSelect: 999,
            minSelect: 0,
            name: 'labs',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: 'date3953013030',
            max: '',
            min: '',
            name: 'startdate',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            hidden: false,
            id: 'date2440358909',
            max: '',
            min: '',
            name: 'enddate',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        indexes: [],
        system: false,
      },
      {
        id: 'pbc_1687431684',
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        name: 'events',
        type: 'base',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1999537002',
            max: 0,
            min: 0,
            name: 'identifier',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text724990059',
            max: 0,
            min: 0,
            name: 'title',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'date2675529103',
            max: '',
            min: '',
            name: 'start',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            hidden: false,
            id: 'date16528305',
            max: '',
            min: '',
            name: 'end',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_1687431684',
            hidden: false,
            id: 'relation3002904518',
            maxSelect: 999,
            minSelect: 0,
            name: 'linkedevent',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: 'json418873732',
            maxSize: 0,
            name: 'milestones',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
        ],
        indexes: [],
        system: false,
      },
      {
        id: 'pbc_2691397795',
        listRule: '@request.headers.x_arcade_token != ""',
        viewRule: '@request.headers.x_arcade_token != ""',
        createRule: null,
        updateRule: null,
        deleteRule: null,
        name: 'labs',
        type: 'base',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text724990059',
            max: 0,
            min: 0,
            name: 'title',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text2809261753',
            max: 0,
            min: 0,
            name: 'labcode',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        indexes: [],
        system: false,
      },
      {
        id: 'pbc_3414089001',
        listRule: '@request.auth.email ?~ "@ekraf.dev" && @request.headers.x_arcade_token != ""',
        viewRule: '@request.auth.email ?~ "@ekraf.dev" && @request.headers.x_arcade_token != ""',
        createRule: null,
        updateRule: '@request.auth.email ?~ "@ekraf.dev" && @request.headers.x_arcade_token != ""',
        deleteRule: null,
        name: 'profiles',
        type: 'base',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1579384326',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'number666537513',
            max: null,
            min: null,
            name: 'points',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_955655590',
            hidden: false,
            id: 'relation1325220553',
            maxSelect: 999,
            minSelect: 0,
            name: 'earned_courses',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text2465036164',
            max: 0,
            min: 0,
            name: 'program',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'bool2656357830',
            name: 'ranked',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'select2755300790',
            maxSelect: 1,
            name: 'facilitator',
            presentable: false,
            required: false,
            system: false,
            type: 'select',
            values: ['india', 'indonesia'],
          },
          {
            exceptDomains: [],
            hidden: false,
            id: 'url376926767',
            name: 'avatar',
            onlyDomains: [],
            presentable: false,
            required: false,
            system: false,
            type: 'url',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        indexes: [],
        system: false,
      },
      {
        id: 'pbc_663908841',
        listRule: '@request.headers.x_arcade_token != ""',
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        name: 'course_stats',
        type: 'view',
        fields: [
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text3208210256',
            max: 0,
            min: 0,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: '_clone_Y4eq',
            max: 0,
            min: 0,
            name: 'title',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'number74588000',
            max: null,
            min: null,
            name: 'enrollment_count',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            hidden: false,
            id: 'number1157329626',
            max: null,
            min: null,
            name: 'diff_hard',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            hidden: false,
            id: 'number1034508212',
            max: null,
            min: null,
            name: 'diff_medium',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            hidden: false,
            id: 'number3431790495',
            max: null,
            min: null,
            name: 'diff_easy',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
        ],
        indexes: [],
        system: false,
        viewQuery:
          "SELECT\n  c.id AS id,\n  c.title,\n  COUNT(e.id) AS enrollment_count,\n  COUNT(CASE WHEN e.difficulty = 'hard' THEN 1 END) AS diff_hard,\n  COUNT(CASE WHEN e.difficulty = 'medium' THEN 1 END) AS diff_medium,\n  COUNT(CASE WHEN e.difficulty = 'easy' THEN 1 END) AS diff_easy\nFROM courses c\nLEFT JOIN course_enrollments e ON e.course = c.id\nGROUP BY c.id;\n",
      },
    ];

    return app.importCollections(snapshot, false);
  },
  (app) => {
    return null;
  },
);

